version: "3.9"

services:
  tor-browser:
    build:
      context: ./tor_browser
    container_name: tor-browser
    ports:
      - "5800:5800"
    environment:
      TZ: Europe/Madrid
    volumes:
      - tor-browser-config:/config
    restart: unless-stopped

  i2p-browser:
    build:
      context: ./i2p
    container_name: i2p-browser
    ports:
      - "5801:5800"
      - "5901:5900"
      - "4444:4444"
      - "4447:4447"
      - "7657:7657"
    environment:
      TZ: Etc/UTC
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 800
      KEEP_APP_RUNNING: 1
    volumes:
      - i2p-config:/config
    restart: unless-stopped

volumes:
  tor-browser-config:
  i2p-config:
